version: "3.8"

name: genesis_prod

services:
  server:
    environment: 
      - NODE_ENV=prod
    restart: always
    build: server
    command: npm run start:prod
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client/dist:/usr/share/nginx/html
      - ./nginx/prod:/etc/nginx/genesis
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

